# Imagen oficial de Node
FROM node:24

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copia únicamente los archivos de dependencias
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del proyecto
COPY . .

# Puerto utilizado por Vite
EXPOSE 5173

# Ejecuta el servidor de desarrollo
CMD ["npm", "run", "dev", "--", "--host"]