import {
  createIcons,
  Search,
  CircleUserRound,
  Heart,
  Star,
  Compass,
  Landmark,
  Leaf,
  Trees,
  Utensils,
  UtensilsCrossed,
  Church,
  ShoppingBag,
  ChevronLeft,
  ChevronRight,
  ArrowLeft,
  MapPin,
  Clock,
  LayoutGrid,
  ExternalLink,
  MapPinCheck,
  LocateFixed,
  Trophy,
  Gift,
  Map,
  Globe,
  // Panel de administración
  Gauge,
  UsersRound,
  MapPinned,
  Target,
  Ticket,
  SlidersHorizontal,
  LogOut,
  CircleCheck,
  TriangleAlert,
  Package,
  SquarePen,
  RefreshCw,
  Trash2,
  ShieldCheck,
  // Menú de perfil
  LogIn,
  UserPlus,
  // Estados y avisos
  Check,
  Lock,
  ShieldAlert,
  X,
  // Dashboard de usuario
  LayoutDashboard,
  // Moderación
  MessageSquareWarning,
  // Filtros de recompensas
  PackageCheck,
  Wallet,
  // Mapa / detalle de POI
  Route
} from "lucide";

// Todo icono referenciado en el HTML vía data-lucide="..." debe estar aquí.
// Si falta, Lucide no reemplaza el <i> (queda vacío) Y deja un
// `console.warn` por cada icono ausente en cada repintado -createIcons()
// corre en cada render- así que un solo icono sin registrar puede inundar la
// consola. Mantener esta lista sincronizada con los data-lucide del proyecto
// evita ambas cosas.
export const loadIcons = () => {
  createIcons({
    icons: {
      Search,
      CircleUserRound,
      Heart,
      Star,
      Compass,
      Landmark,
      Leaf,
      Trees,
      Utensils,
      UtensilsCrossed,
      Church,
      ShoppingBag,
      ChevronLeft,
      ChevronRight,
      ArrowLeft,
      MapPin,
      Clock,
      LayoutGrid,
      ExternalLink,
      MapPinCheck,
      LocateFixed,
      Trophy,
      Gift,
      Map,
      Globe,
      Gauge,
      UsersRound,
      MapPinned,
      Target,
      Ticket,
      SlidersHorizontal,
      LogOut,
      CircleCheck,
      TriangleAlert,
      Package,
      SquarePen,
      RefreshCw,
      Trash2,
      ShieldCheck,
      LogIn,
      UserPlus,
      Check,
      Lock,
      ShieldAlert,
      X,
      LayoutDashboard,
      MessageSquareWarning,
      PackageCheck,
      Wallet,
      Route
    },
  });
};
